{include file='shared/htmlheader.tpl'}

<h2>Help & Support</h2>

<p><em>The help and support section is under construction. In the meantime please
see the HTML files within the "docs" directory for general information on
{$smarty.const.APP_TITLE}.</em></p>

<p>A call detail record (also known as call data record or CDR) is the computer
record produced by a telephone exchange containing details of a phone call that
passed through it. It is the automated equivalent of the paper toll tickets that
were written and timed by operators for long-distance calls in a manual telephone
exchange.</p>

<p>{$smarty.const.LONG_TITLE} ({$smarty.const.APP_TITLE}) is a PHP application
designed to work with data generated by the
<a href="http://www.voip-info.org/wiki/view/Asterisk+cdr+mysql">Asterisk MySQL CDR add-on</a>.
It produces periodical reports on the usage of your Asterisk PBX and uses
<a href="http://code.google.com/apis/chart/">Google Chart Tools</a> to produce
dynamic visualisations of call volumes. {$smarty.const.APP_TITLE} supports multiple
database servers allowing you to monitor all the Asterisk servers for which you are
responsible from one installation of AGCDR.</p>

{include file='shared/htmlfooter.tpl'}